### PR TITLE
Updated some code

### PR DESCRIPTION
**Pull request by maximjsx**
Split code into methods and refactored some stuff .. just look in my commits

### CODE REVIEW

**Comment by Benoit-V** [comment]
I can accept if you remove these two changes because there is a switch in the case if there will be an other database type in the future and the enum structure allow to do a copy paste easily
chrome_KC2WTpqSag
chrome_z2apZV7Z3J

**Comment by maximjsx** [comment]
Okay i can do this but you actually dont need a semicolon in the enum

**Comment by Benoit-V** [comment]
ok

**Comment by maximjsx** [comment]
So what about now?

**Comment by maximjsx** [comment]
https://github.com/BebeDlaStreat/DiscordRankSync/pull/4/commits/62d4d960bf078507ef495b553378c874a8cdfb6a

**Pull request merged**
